server:
  port: 7001
  servlet:
    context-path: /coupon-template

spring:
  application:
    name: eureka-client-coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/coupon?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: couponHikariCP
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 10000ms

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: coupon-template
    groupId: coupon-service
    artifactId: coupon-template
    version: 1.0-SNAPSHOT
logging:
  level:
    com.source.coupon: debug
