spring:
  application:
    name: coupon-eureka

server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    # 是否从Eureka-Server 中获取注册信息，默认为true
    # 如果是一个单节点的Eureka-Server，不需要同步节点的
    # 数据，设置为false
    fetch-registry: false
    # 是否将自己注册到Eureka-Server中，默认为true
    # 由于当前应用是单节点的Eureka-Server，需要设置为false
    register-with-eureka: false
    service-url:
      # 设置 Eureka-Server 所在的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

