#spring:
#  application:
#    name: homepage-eureka
#server:
#  port: 8000
#
##eureka配置
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    # 是否从 eurekaServer 中获取注册信息(默认为true)
#    fetch-registry: false
#    # 是否将自己注册到其他的 eurekaServer，默认为true
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
